// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408082808_InitialScaffold")]
    partial class InitialScaffold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByPartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupporterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DonationId");

                    b.HasIndex(new[] { "SupporterId" }, "IX_Donations_SupporterId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Backend.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AllocationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllocationId");

                    b.HasIndex(new[] { "DonationId" }, "IX_DonationAllocations_DonationId");

                    b.HasIndex(new[] { "SafehouseId" }, "IX_DonationAllocations_SafehouseId");

                    b.ToTable("DonationAllocations");
                });

            modelBuilder.Entity("Backend.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttendanceRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchoolName")
                        .HasColumnType("TEXT");

                    b.HasKey("EducationRecordId");

                    b.HasIndex(new[] { "ResidentId" }, "IX_EducationRecords_ResidentId");

                    b.ToTable("EducationRecords");
                });

            modelBuilder.Entity("Backend.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("DentalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MedicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NutritionScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("PsychologicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("HealthRecordId");

                    b.HasIndex(new[] { "ResidentId" }, "IX_HealthWellbeingRecords_ResidentId");

                    b.ToTable("HealthWellbeingRecords");
                });

            modelBuilder.Entity("Backend.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinationKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("HomeVisit");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowUpNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafetyConcernsNoted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VisitationId");

                    b.HasIndex(new[] { "ResidentId" }, "IX_HomeVisitations_ResidentId");

                    b.ToTable("HomeVisitations");
                });

            modelBuilder.Entity("Backend.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedUnitValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex(new[] { "DonationId" }, "IX_InKindDonationItems_DonationId");

                    b.ToTable("InKindDonationItems");
                });

            modelBuilder.Entity("Backend.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowUpRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IncidentId");

                    b.HasIndex(new[] { "ResidentId" }, "IX_IncidentReports_ResidentId");

                    b.HasIndex(new[] { "SafehouseId" }, "IX_IncidentReports_SafehouseId");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("Backend.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.HasIndex(new[] { "ResidentId" }, "IX_InterventionPlans_ResidentId");

                    b.ToTable("InterventionPlans");
                });

            modelBuilder.Entity("Backend.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Backend.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AssignmentStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.HasIndex(new[] { "PartnerId" }, "IX_PartnerAssignments_PartnerId");

                    b.HasIndex(new[] { "SafehouseId" }, "IX_PartnerAssignments_SafehouseId");

                    b.ToTable("PartnerAssignments");
                });

            modelBuilder.Entity("Backend.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConcernsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionalStateObserved")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressNoted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferralMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecordingId");

                    b.HasIndex(new[] { "ResidentId" }, "IX_ProcessRecordings_ResidentId");

                    b.ToTable("ProcessRecordings");
                });

            modelBuilder.Entity("Backend.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headline")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.ToTable("PublicImpactSnapshots");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseControlNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRiskLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateEnrolled")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfAdmission")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyIndigenous")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyInformalSettler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyIs4ps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyParentPwd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilySoloParent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HasSpecialNeeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialRiskLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsPwd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("PwdType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubCatAtRisk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatChildLabor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatChildWithHiv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatCicl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatOrphaned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatOsaec")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatPhysicalAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatSexualAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatStreetChild")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCatTrafficked")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResidentId");

                    b.HasIndex(new[] { "SafehouseId" }, "IX_Residents_SafehouseId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("Backend.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityGirls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityStaff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SafehouseId");

                    b.ToTable("Safehouses");
                });

            modelBuilder.Entity("Backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveResidents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvgEducationProgress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AvgHealthScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("HomeVisitationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("MonthEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MonthStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessRecordingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MetricId");

                    b.HasIndex(new[] { "SafehouseId" }, "IX_SafehouseMonthlyMetrics_SafehouseId");

                    b.ToTable("SafehouseMonthlyMetrics");
                });

            modelBuilder.Entity("Backend.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgViewDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<int>("CaptionLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickThroughs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationReferrals")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EngagementRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("EstimatedDonationValuePhp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FeaturesResidentStory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Forwards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HasCallToAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hashtags")
                        .HasColumnType("TEXT");

                    b.Property<int>("Impressions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsBoosted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<int>("MentionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumHashtags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileVisits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saves")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId");

                    b.ToTable("SocialMediaPosts");
                });

            modelBuilder.Entity("Backend.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupporterId");

                    b.ToTable("Supporters");
                });

            modelBuilder.Entity("Backend.Models.__EFMigrationsLock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("__EFMigrationsLock", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.HasOne("Backend.Models.Supporter", "Supporter")
                        .WithMany("Donations")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Backend.Models.DonationAllocation", b =>
                {
                    b.HasOne("Backend.Models.Donation", "Donation")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.EducationRecord", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("EducationRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("HealthWellbeingRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.HomeVisitation", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("HomeVisitations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.InKindDonationItem", b =>
                {
                    b.HasOne("Backend.Models.Donation", "Donation")
                        .WithMany("InKindDonationItems")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("Backend.Models.IncidentReport", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("IncidentReports")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("IncidentReports")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.InterventionPlan", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.PartnerAssignment", b =>
                {
                    b.HasOne("Backend.Models.Partner", "Partner")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partner");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.ProcessRecording", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("ProcessRecordings")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("Residents")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("SafehouseMonthlyMetrics")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("InKindDonationItems");
                });

            modelBuilder.Entity("Backend.Models.Partner", b =>
                {
                    b.Navigation("PartnerAssignments");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.Navigation("EducationRecords");

                    b.Navigation("HealthWellbeingRecords");

                    b.Navigation("HomeVisitations");

                    b.Navigation("IncidentReports");

                    b.Navigation("InterventionPlans");

                    b.Navigation("ProcessRecordings");
                });

            modelBuilder.Entity("Backend.Models.Safehouse", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("IncidentReports");

                    b.Navigation("PartnerAssignments");

                    b.Navigation("Residents");

                    b.Navigation("SafehouseMonthlyMetrics");
                });

            modelBuilder.Entity("Backend.Models.Supporter", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
